version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: task-manager
    environment:
      POSTGRES_DB: task-manager-db
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
  api:
    depends_on:
      - db
    build:
      dockerfile: Dockerfile
      context: .
      target: development
    volumes:
      - .:/usr/src/app
    env_file:
      - .env
    command: npm run start:dev
    ports:
      - 3000:3000

