version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: task-manager
    environment:
      POSTGRES_DB: task-manager-db
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
